### ISSUE TITLE
Add to apple wallet not working

### ISSUE THREAD

**Issue by korgoth** [GreenPassApp/greenpass-app#31]
Its been months since i have used the app (both when it was in beta and when it was released to the Appstore) and i am still not able to add my certificate to apple wallet. In the beta version i was presented with a web page which returned 500 (internal server error) and in the current release from the App store i am getting a popup stating: Could not retrieve Apple Wallet Pass. Please ensure that you are connected to the internet. And while i am connected - a little digging thru the network requests shows that the app is still getting error 500 (internal server error). 

Does anyone have any idea why is this and is it fixable?

**Comment by JakobStadlhuber** [comment]
This is fixed in the new versions, please just download it from the AppStore on iOS oder on the website for Android.

**Comment by korgoth** [comment]
I am currently on iOS, and using app version 1.20 (latest release i see on github and in the AppStore) and the problem persist for me. Same error.
